### PR TITLE
Correct way of passing dynamic service id

### PR DESCRIPTION
**Pull request by 4ernovm**
It shows "You cannot dump a container with parameters that contain references to other services" error otherwise

### CODE REVIEW

**Comment by scaytrase** [comment]
@4ernovm could you please also check DI instantiations? Tests failed

**Comment by 4ernovm** [comment]
Damn it! This expression syntax stuff was added starting from 2.4...

**Comment by scaytrase** [comment]
@4ernovm  actually we can just require `symfony/expression-language` `~2.4` as an mandatory requirement, as it does not requires any dependencies by itself.

Are you sure this way of referencing services via parameters is correct? Could you provide some docs on it?

**Comment by scaytrase** [comment]
I'm thinking of implementing compiler pass for configuring service instead of direct yaml configuration, like [here](https://github.com/scaytrase/symfony-sms-interface/blob/master/src/ScayTrase/SmsDeliveryBundle/DependencyInjection/Compiler/SpoolCompilerPass.php#L39)

**Comment by 4ernovm** [comment]
I'm not 100% sure it's correct. I found it in symfony cookbook. But I'm sure, that the way it was before is not good either, because Symfony 2.7 throws error on it. So maybe using compiler pass will be better solution in this case. P.S. Don't forget to switch params in here https://github.com/4ernovm/symfony-websms-bundle/commit/5b6e64f43f1bb6a539a04fbf82423d5eea67fde2

**Comment by scaytrase** [comment]
I've already cherry-picked your commit to another branch, thanks. Experimenting with DI too.

**Comment by 4ernovm** [comment]
I guess this can be closed

**Comment by scaytrase** [comment]
Ok, thanks for other fixes. I'll think on correct DI

**Pull request closed without merging**
